# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_auto_20160519_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Image',
            field=models.ImageField(upload_to=b'/home/brserver1/safestreet/serverPothole/media/images', verbose_name=b'Image'),
        ),
    ]
