# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20160530_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Image',
            field=models.ImageField(upload_to=b'/home/testbed/pothole/serverPothole/media/images', verbose_name=b'Image'),
        ),
    ]
