# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_auto_20160608_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Image',
            field=models.ImageField(upload_to='/home/vikrant/PycharmProjects/serverPothole/media/images', verbose_name='Image'),
        ),
    ]
