# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_auto_20161122_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Image',
            field=models.ImageField(upload_to='/home/brserver1/safestreet2/serverPothole/media/images', verbose_name='Image'),
        ),
    ]
