# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_auto_20170128_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Image',
            field=models.ImageField(upload_to='/home/brserver1/safestreet2/serverPothole/media/images', verbose_name='Image'),
        ),
    ]
