# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_auto_20170128_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Image',
            field=models.ImageField(upload_to='/home/vikrant/PycharmProjects/serverPothole/media/images', verbose_name='Image'),
        ),
    ]
