# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
