# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-22 21:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pothole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedpotholes',
            name='classifier_output',
            field=models.CharField(default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='automatedpotholes',
            name='detection_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='automatedpotholes',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='automatedpotholes',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
