# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_pothole', '0002_auto_20160522_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(default=b'D', max_length=1)),
                ('start_latitude', models.FloatField(null=True)),
                ('stop_latitude', models.FloatField(null=True)),
                ('start_longitude', models.FloatField(null=True)),
                ('stop_longitude', models.FloatField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('stop_time', models.DateTimeField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('app_version', models.TextField()),
                ('pothole_count', models.IntegerField(null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
