# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pothole', '0003_ridedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridedetails',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='start_longitude',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='stop_latitude',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='stop_longitude',
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
