# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-05 22:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pothole', '0004_auto_20160603_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedpotholes',
            name='pred_prob',
            field=models.FloatField(null=True),
        ),
    ]
