# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pothole', '0005_automatedpotholes_pred_prob'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedpotholes',
            name='partial_distance',
            field=models.FloatField(null=True),
        ),
    ]
