# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 19:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pothole', '0006_automatedpotholes_partial_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedetails',
            name='phone_model',
            field=models.TextField(null=True),
        ),
    ]
