# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pothole', '0007_ridedetails_phone_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automatedpotholes',
            old_name='pred_prob',
            new_name='intensity_score',
        ),
    ]
