# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pothole', '0008_auto_20160608_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automatedpotholes',
            old_name='intensity_score',
            new_name='classifier_intensity',
        ),
        migrations.AddField(
            model_name='automatedpotholes',
            name='classifier_probability',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='automatedpotholes',
            name='event_speed',
            field=models.FloatField(null=True),
        ),
    ]
