# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pothole', '0009_auto_20160611_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedpotholes',
            name='classifier_output',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='automatedpotholes',
            name='vehicle_type',
            field=models.CharField(default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='vehicle_type',
            field=models.CharField(default='D', max_length=1),
        ),
    ]
