# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160518_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Credit',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='DeActivate',
            new_name='deactivate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='HomeLocation',
            new_name='home_location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Rating',
            new_name='rating',
        ),
    ]
